#!/usr/bin/env python3

import argparse
import heroku_deploy

parser = argparse.ArgumentParser(
    description="Describe the bentoml bundle deployed to Heroku",
    epilog="Check out https://github.com/bentoml/heroku-deploy to know more",
)
parser.add_argument(
    "deployment_name", help="The name you used for your deployment"
)
args = parser.parse_args()

heroku_deploy.describe(args.deployment_name)