#!/usr/bin/env python3

import argparse
import os
import heroku_deploy

parser = argparse.ArgumentParser(
    description="Update the bentoml bundle on Heroku",
    epilog="Check out https://github.com/bentoml/heroku-deploy to know more",
)
parser.add_argument(
    "bento_bundle_path", help="Path to bentoml bundle"
)
parser.add_argument(
    "deployment_name", help="The name you want to use for your deployment"
)
parser.add_argument(
    "config_json",
    help="(optional) The config file for your deployment",
    default=os.path.join(os.getcwd(), "heroku_config.json"),
    nargs="?",
)
args = parser.parse_args()

heroku_config = heroku_deploy.get_configuration_value(args.config_json)
heroku_deploy.update(args.bento_bundle_path, args.deployment_name, heroku_config)
print("Update Complete!")